<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="2" passed="0">
  <reporter-output>
    <line>
      <![CDATA[Request Number for TC3 new role is 2351093]]>
    </line>
    <line>
      <![CDATA[Request Number for TC3 remove role is 2351050]]>
    </line>
  </reporter-output>
  <suite name="Default suite" duration-ms="298997" started-at="2018-09-28T11:14:26Z" finished-at="2018-09-28T11:19:25Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="298997" started-at="2018-09-28T11:14:26Z" finished-at="2018-09-28T11:19:25Z">
      <class name="com.bp.saviynt.TestCase1">
        <test-method status="PASS" signature="openApplication()[pri:0, instance:com.bp.saviynt.TestCase1@66d18979]" name="openApplication" is-config="true" duration-ms="20764" started-at="2018-09-28T11:14:26Z" finished-at="2018-09-28T11:14:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openApplication -->
        <test-method status="FAIL" signature="TC2()[pri:2, instance:com.bp.saviynt.TestCase1@66d18979]" name="TC2" duration-ms="129189" started-at="2018-09-28T11:14:46Z" finished-at="2018-09-28T11:16:56Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[All end points were not present expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: All end points were not present expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at com.bp.saviynt.TestCase1.TC2(TestCase1.java:283)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC2 -->
        <test-method status="PASS" signature="CloseApplication(org.testng.ITestResult)[pri:0, instance:com.bp.saviynt.TestCase1@66d18979]" name="CloseApplication" is-config="true" duration-ms="1678" started-at="2018-09-28T11:16:56Z" finished-at="2018-09-28T11:16:57Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=TC2 status=FAILURE method=TestCase1.TC2()[pri:2, instance:com.bp.saviynt.TestCase1@66d18979] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CloseApplication -->
        <test-method status="PASS" signature="openApplication()[pri:0, instance:com.bp.saviynt.TestCase1@66d18979]" name="openApplication" is-config="true" duration-ms="19646" started-at="2018-09-28T11:16:57Z" finished-at="2018-09-28T11:17:17Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openApplication -->
        <test-method status="FAIL" signature="TC3()[pri:3, instance:com.bp.saviynt.TestCase1@66d18979]" name="TC3" duration-ms="126330" started-at="2018-09-28T11:17:17Z" finished-at="2018-09-28T11:19:23Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[All end points were not present expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: All end points were not present expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at com.bp.saviynt.TestCase1.TC3(TestCase1.java:418)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Request Number for TC3 new role is 2351093]]>
            </line>
            <line>
              <![CDATA[Request Number for TC3 remove role is 2351050]]>
            </line>
          </reporter-output>
        </test-method> <!-- TC3 -->
        <test-method status="PASS" signature="CloseApplication(org.testng.ITestResult)[pri:0, instance:com.bp.saviynt.TestCase1@66d18979]" name="CloseApplication" is-config="true" duration-ms="1346" started-at="2018-09-28T11:19:23Z" finished-at="2018-09-28T11:19:25Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=TC3 status=FAILURE method=TestCase1.TC3()[pri:3, instance:com.bp.saviynt.TestCase1@66d18979] output=Request Number for TC3 new role is 2351093]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CloseApplication -->
      </class> <!-- com.bp.saviynt.TestCase1 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
